# Generated by Django 5.2.2 on 2025-08-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_parking_totalvacancies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='totalVacancies',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
