# Generated by Django 5.2.2 on 2025-06-09 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicleType', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=7)),
                ('entryDate', models.DateTimeField()),
                ('vehicleType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleType.vehicletype')),
            ],
        ),
    ]
