# Generated by Django 5.2.2 on 2025-06-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entryRecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryrecord',
            name='entryDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
