# Generated by Django 5.2.2 on 2025-06-09 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entryRecord', '0001_initial'),
        ('paymentType', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exitDate', models.DateTimeField()),
                ('finalValue', models.DecimalField(decimal_places=2, max_digits=5)),
                ('entryRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entryRecord.entryrecord')),
                ('paymentType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paymentType.paymenttype')),
            ],
        ),
    ]
