# Generated by Django 5.2.2 on 2025-06-18 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exitRecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitrecord',
            name='exitDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exitrecord',
            name='finalValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
