# Generated by Django 5.2.2 on 2025-08-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exitRecord', '0002_alter_exitrecord_exitdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitrecord',
            name='finalValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
